name: fintrack
description: "一个Flutter记账应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # 数据库
  sqflite: ^2.3.2
  sqflite_common_ffi_web: ^0.4.2+2
  path: ^1.9.0
  # 状态管理
  provider: ^6.1.2
  # 日期格式化
  intl: ^0.19.0
  # 图表
  fl_chart: ^0.66.2
  # 本地存储
  shared_preferences: ^2.2.2
  # UUID生成
  uuid: ^4.3.3
  # 图标
  font_awesome_flutter: ^10.7.0
  # HTTP请求
  http: ^1.2.1
  # 本地通知
  flutter_local_notifications: ^17.2.2
  # 时区支持
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  excel: ^2.1.0
  file_picker: ^10.1.9
  csv: ^5.1.1
  grouped_list: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/transactions.json

  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
